function redirectToRandomWebsite(tabId) {
  var updateProperties = {
    url: pickRandomWebsite()
  };
  chrome.tabs.update(tabId, updateProperties);
}

function pickRandomWebsite() {
  var sitesList = [
    "http://heeeeeeeey.com/",
    "http://tinytuba.com/",
    "http://corndog.io/",
    "http://thatsthefinger.com/",
    "http://cant-not-tweet-this.com/",
    "http://weirdorconfusing.com/",
    "http://eelslap.com/",
    "http://www.staggeringbeauty.com/",
    "http://endless.horse/",
    "http://www.trypap.com/",
    "http://www.republiquedesmangues.fr/",
    "http://www.movenowthinklater.com/",
    "http://www.partridgegetslucky.com/",
    "http://beesbeesbees.com/",
    "http://www.koalastothemax.com/",
    "http://www.everydayim.com/",
    "http://randomcolour.com/",
    "http://isitwednesdaymydudes.ml/",
    "http://hasthelargehadroncolliderdestroyedtheworldyet.com/",
    "http://ninjaflex.com/",
    "http://ihasabucket.com/",
    "http://corndogoncorndog.com/",
    "https://pointerpointer.com",
    "http://imaninja.com/",
    "http://www.ismycomputeron.com/",
    "http://www.yesnoif.com/",
    "http://iamawesome.com/",
    "http://www.pleaselike.com/",
    "http://crouton.net/",
    "http://corgiorgy.com/",
    "http://www.wutdafuk.com/",
    "http://unicodesnowmanforyou.com/",
    "http://www.crossdivisions.com/",
    "http://tencents.info/",
    "http://www.patience-is-a-virtue.org/",
    "http://whitetrash.nl/",
    "http://www.theendofreason.com/",
    "http://pixelsfighting.com/",
    "http://baconsizzling.com/",
    "http://isitwhite.com/",
    "http://onemillionlols.com/",
    "http://www.omfgdogs.com/",
    "http://oct82.com/",
    "http://chihuahuaspin.com/",
    "http://www.blankwindows.com/",
    "http://dogs.are.the.most.moe/",
    "http://tunnelsnakes.com/",
    "http://www.infinitething.com/",
    "http://www.trashloop.com/",
    "http://www.ascii-middle-finger.com/",
    "http://www.coloursquares.com/",
    "http://spaceis.cool/",
    "http://buildshruggie.com/",
    "http://buzzybuzz.biz/",
    "http://yeahlemons.com/",
    "http://burnie.com/",
    "http://wowenwilsonquiz.com",
  ];
  return sitesList[Math.floor(Math.random() * sitesList.length)];
}
